// <auto-generated />
using System;
using Events.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Events.Api.Data.Migrations
{
    [DbContext(typeof(EventsDbContext))]
    [Migration("20260705202528_AddAiRecommendationHistory")]
    partial class AddAiRecommendationHistory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Events.Api.Entities.AiRecommendationRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Preferences")
                        .HasColumnType("text")
                        .HasColumnName("preferences");

                    b.Property<string>("ResultsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("results");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_ai_recommendation_requests");

                    b.HasIndex("UserId", "CreatedAtUtc")
                        .HasDatabaseName("ix_ai_recommendation_requests_user_id_created_at_utc");

                    b.ToTable("ai_recommendation_requests", (string)null);
                });

            modelBuilder.Entity("Events.Api.Entities.Category", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc")
                        .HasDefaultValueSql("now()");

                    b.HasKey("CategoryId")
                        .HasName("pk_categories");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_categories_parent_id");

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("Events.Api.Entities.Event", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("event_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int?>("Capacity")
                        .HasColumnType("integer")
                        .HasColumnName("capacity");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTimeOffset>("EndAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_at_utc");

                    b.Property<bool>("IsVirtual")
                        .HasColumnType("boolean")
                        .HasColumnName("is_virtual");

                    b.Property<decimal?>("Price")
                        .HasColumnType("numeric")
                        .HasColumnName("price");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("slug");

                    b.Property<DateTimeOffset>("StartAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("timezone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("title");

                    b.Property<Guid?>("UmbracoContentKey")
                        .HasColumnType("uuid")
                        .HasColumnName("umbraco_content_key");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("VenueName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("venue_name");

                    b.HasKey("EventId")
                        .HasName("pk_events");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_events_slug");

                    b.HasIndex("StartAtUtc")
                        .HasDatabaseName("ix_events_start_at_utc");

                    b.HasIndex("UmbracoContentKey")
                        .IsUnique()
                        .HasDatabaseName("ix_events_umbraco_content_key");

                    b.ToTable("events", null, t =>
                        {
                            t.HasCheckConstraint("ck_events_status", "status IN ('Draft','Published','Cancelled','Completed')");
                        });
                });

            modelBuilder.Entity("Events.Api.Entities.EventCategory", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.HasKey("EventId", "CategoryId")
                        .HasName("pk_event_categories");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_event_categories_category_id");

                    b.ToTable("event_categories", (string)null);
                });

            modelBuilder.Entity("Events.Api.Entities.EventRegistration", b =>
                {
                    b.Property<Guid>("RegistrationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("registration_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset?>("CancelledAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at_utc");

                    b.Property<DateTimeOffset?>("CheckedInAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("checked_in_at_utc");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<Guid?>("QrMediaKey")
                        .HasColumnType("uuid")
                        .HasColumnName("qr_media_key");

                    b.Property<string>("QrSyncError")
                        .HasColumnType("text")
                        .HasColumnName("qr_sync_error");

                    b.Property<DateTimeOffset>("RegisteredAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registered_at_utc")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("TicketCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("ticket_code");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("RegistrationId")
                        .HasName("pk_event_registrations");

                    b.HasIndex("TicketCode")
                        .IsUnique()
                        .HasDatabaseName("ix_event_registrations_ticket_code");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_event_registrations_user_id");

                    b.HasIndex("EventId", "Status")
                        .HasDatabaseName("ix_event_registrations_event_id_status");

                    b.HasIndex("EventId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_event_registrations_event_id_user_id");

                    b.ToTable("event_registrations", null, t =>
                        {
                            t.HasCheckConstraint("ck_event_registrations_status", "status IN ('Registered','Waitlisted','Cancelled','CheckedIn')");
                        });
                });

            modelBuilder.Entity("Events.Api.Entities.EventTrackingLog", b =>
                {
                    b.Property<long>("TrackingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("tracking_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("TrackingId"));

                    b.Property<Guid?>("AnonymousId")
                        .HasColumnType("uuid")
                        .HasColumnName("anonymous_id");

                    b.Property<Guid?>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("event_type");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("SessionId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("session_id");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("TrackingId")
                        .HasName("pk_event_tracking_log");

                    b.HasIndex("EventId", "OccurredAtUtc")
                        .HasDatabaseName("ix_event_tracking_log_event_id_occurred_at_utc");

                    b.HasIndex("UserId", "OccurredAtUtc")
                        .HasDatabaseName("ix_event_tracking_log_user_id_occurred_at_utc");

                    b.ToTable("event_tracking_log", (string)null);
                });

            modelBuilder.Entity("Events.Api.Entities.Category", b =>
                {
                    b.HasOne("Events.Api.Entities.Category", null)
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .HasConstraintName("fk_categories_categories_parent_id");
                });

            modelBuilder.Entity("Events.Api.Entities.EventCategory", b =>
                {
                    b.HasOne("Events.Api.Entities.Category", "Category")
                        .WithMany("EventCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_event_categories_categories_category_id");

                    b.HasOne("Events.Api.Entities.Event", "Event")
                        .WithMany("EventCategories")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_event_categories_events_event_id");

                    b.Navigation("Category");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("Events.Api.Entities.EventRegistration", b =>
                {
                    b.HasOne("Events.Api.Entities.Event", "Event")
                        .WithMany("Registrations")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_event_registrations_events_event_id");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("Events.Api.Entities.Category", b =>
                {
                    b.Navigation("EventCategories");
                });

            modelBuilder.Entity("Events.Api.Entities.Event", b =>
                {
                    b.Navigation("EventCategories");

                    b.Navigation("Registrations");
                });
#pragma warning restore 612, 618
        }
    }
}
